version: '3.7'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - '3306:3306'
  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
