name: sqldef
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  test:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.13
      - uses: actions/checkout@v2

      - run: docker-compose up -d
      - run: make test
        env:
          MYSQL_HOST: 127.0.0.1
          PGHOST: 127.0.0.1
          PGSSLMODE: disable

  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.13
      - uses: actions/checkout@v2

      - run: make package

